---
title: "North Carolina's Arts Economy Mapped"
author: "By Duke undergraduates: Georgie Stammer, Suresh Kannoth, & Oliver Hess"
date: 'Created April, 2023'
output: html_document
---

```{r include = FALSE}
knitr::opts_chunk$set(include = FALSE)
```

```{r choose-data-files}
# Edit this section to use datasets from different years
# This will work best if the format of the dataset is the same as the original 2021 datasets taken from the BEA & OSBM
# If the format is different, then further code alterations will be necessary in order to make the data work with the map

# Population data should be from the NC OSBM's dataset "County Population Totals"
# URL as of April, 2023: https://demography.osbm.nc.gov/explore/dataset/county-population-totals/export/?disjunctive.county&disjunctive.region&disjunctive.cog&disjunctive.msa&disjunctive.vintage&disjunctive.estimateprojection
# To retrieve the correct link go to the Export tab, and locate the CSV option.
# RIGHT-CLICK "Whole dataset" next to CSV & choose to copy the link address. Paste this address in the quotations below:

populationDataSource <- "https://demography.osbm.nc.gov/api/explore/v2.1/catalog/datasets/county-population-totals/exports/csv?lang=en&timezone=America%2FNew_York&use_labels=true&delimiter=%3B"

# GDP & employment data should be from the BEA's interactive data tables.
# Follow the URLs here (April, 2023), or the steps below.
# GDP data: https://apps.bea.gov/itable/?ReqID=70&step=1&acrdn=5#eyJhcHBpZCI6NzAsInN0ZXBzIjpbMSwyNCwyOSwyNSwzMSwyNiwyNywzMF0sImRhdGEiOltbIlRhYmxlSWQiLCI1MDEiXSxbIkNsYXNzaWZpY2F0aW9uIiwiTkFJQ1MiXSxbIk1ham9yX0FyZWEiLCI0Il0sWyJTdGF0ZSIsWyIzNzAwMCJdXSxbIkFyZWEiLFsiWFgiXV0sWyJTdGF0aXN0aWMiLFsiNzYiXV0sWyJVbml0X29mX21lYXN1cmUiLCJMZXZlbHMiXSxbIlllYXIiLFsiMjAyMSJdXSxbIlllYXJCZWdpbiIsIi0xIl0sWyJZZWFyX0VuZCIsIi0xIl1dfQ==
# Employment data: https://apps.bea.gov/itable/?ReqID=70&step=1&acrdn=5#eyJhcHBpZCI6NzAsInN0ZXBzIjpbMSwyNCwyOSwyNSwzMSwyNiwyNywzMF0sImRhdGEiOltbIlRhYmxlSWQiLCIzMyJdLFsiQ2xhc3NpZmljYXRpb24iLCJOQUlDUyJdLFsiTWFqb3JfQXJlYSIsIjQiXSxbIlN0YXRlIixbIjM3MDAwIl1dLFsiQXJlYSIsWyJYWCJdXSxbIlN0YXRpc3RpYyIsWyIxNzAwIl1dLFsiVW5pdF9vZl9tZWFzdXJlIiwiTGV2ZWxzIl0sWyJZZWFyIixbIjIwMjEiXV0sWyJZZWFyQmVnaW4iLCItMSJdLFsiWWVhcl9FbmQiLCItMSJdXX0=
# Specifically, within Regional Data: GDP and Personal Income
# Select "Gross domestic product (GDP) by county and metropolitan area" for GDP data or "Personal income and employment by county and metropolitan area" for employment data
# Then specify Major Area = County, State = NC, Area = All counties, Statistic = GDP/employment in Arts, Entertainment, and Recreation, & desired year
# When you have reached the desired dataset, download it as a CSV and put this CSV into the "data" folder. Then paste the file's name into the quotations below:

GDPDataSource <- "Arts-GDP-2021.csv"
JobsDataSource <- "Arts-Employment-2021.csv"

```

```{r set-up-libraries}
library(leaflet)
library(geojsonsf)
library(tidyverse)
library(sf)
library(sp)
library(spdplyr)
library(htmlwidgets)
```

```{r geodata-setup}
geo_data <- geojson_sf("data/north-carolina-geographic-regions.geojson")

geo_clean <- geo_data %>%
  filter(region_type == "Other // Region") %>%
  select(county)

```

```{r population-setup}
# current data reflects 2021 estimates
pop_data <- read.csv(populationDataSource, sep = ";")

pop_clean <- pop_data %>%
  filter(Year == 2021, County != "State") %>%
  rename(Population = Value) %>%
  select(County, Population) %>%
  rename(county = County)

```


```{r GDP-map-setup}
artsGDPraw <- read_csv(paste("data/", GDPDataSource, sep = ""), skip = 3)

artsGDP <- artsGDPraw %>%
  mutate(GeoName = substr(GeoName, start = 1, stop = nchar(GeoName) - 4)) %>%
  slice(2:101) %>%
  rename(county = GeoName, ArtsGDP = `2021`) %>%
  select(county, ArtsGDP) %>%
  transform(ArtsGDP = as.numeric(ArtsGDP))

gdp_map <- left_join(geo_clean, artsGDP)

# pop-up info
gdp_map$info <- paste("<strong>",gdp_map$county,"</strong>", "</br>",
                       "Arts GDP: $",
                       prettyNum(gdp_map$ArtsGDP * 1000, big.mark = ","))
```

```{r GDP-PER-CAPITA-map-setup}
gdp_per_cap <- left_join(artsGDP, pop_clean) %>%
  mutate(GDPperCap = (ArtsGDP * 1000) / Population) %>%
  select(county, GDPperCap)

gdppercap_map <- left_join(geo_clean, gdp_per_cap)

# pop-up info
gdppercap_map$info <- paste("<strong>",gdppercap_map$county,"</strong>", "</br>",
                       "Arts GDP Per Capita: $",
                       formatC(gdppercap_map$GDPperCap, big.mark = ",", format = "f", digits = 2))
```


```{r jobs-map-setup}
jobsraw <- read_csv(paste("data/", JobsDataSource, sep = ""), skip = 3)

artsjobs <- jobsraw %>%
  mutate(GeoName = substr(GeoName, start = 1, stop = nchar(GeoName) - 4)) %>%
  slice(2:101) %>%
  rename(county = GeoName, ArtsJobs = `2021`) %>%
  select(county, ArtsJobs) %>%
  transform(ArtsJobs = as.numeric(ArtsJobs))

jobs_map <- left_join(geo_clean, artsjobs)

# pop-up info
jobs_map$info <- paste("<strong>",jobs_map$county,"</strong>", "</br>",
                       "Arts Employment: ",
                       prettyNum(jobs_map$ArtsJobs, big.mark = ","))
```

```{r jobs-PER-CAPITA-map-setup}
jobs_per_cap <- left_join(artsjobs, pop_clean) %>%
  mutate(jobsPerCap = (ArtsJobs * 1000) / Population) %>%
  select(county, jobsPerCap)

jobspercap_map <- left_join(geo_clean, jobs_per_cap)

# pop-up info
jobspercap_map$info <- paste("<strong>",jobspercap_map$county,"</strong>", "</br>",
                       "Arts Jobs Per 1,000 People: ",
                       formatC(jobspercap_map$jobsPerCap, format = "f", digits = 2))
```


```{r preparing-colors}
GDPbins <- c(0, 1000, 5000, 10000, 50000, 100000, 1500000)
GDPlabels <- c("< $1,000,000",
               "$1,000,000 - $5,000,000",
               "$5,000,000 - $10,000,000",
               "$10,000,000 - $50,000,000",
               "$50,000,000 - $100,000,000",
               "> $100,000,000",
               "No data")
GDPColor <- colorBin("YlGn", domain = artsGDP$ArtsGDP, bins = GDPbins)

GDPpercapbins <- c(0, 100, 200, 300, 400, 500, 3000)
GDPpercaplabels <- c("< $100",
               "$100 - $200",
               "$200 - $300",
               "$300 - $400",
               "$400 - $500",
               "> $500",
               "No data")
GDPpercapColor <- colorBin("YlGn", domain = gdp_per_cap$GDPperCap, bins = GDPpercapbins)

jobsbins <- c(0, 100, 500, 1000, 5000, 10000, 25000)
jobslabels <- c("< 100",
               "100 - 500",
               "500 - 1,000",
               "1,000 - 5,000",
               "5,000 - 10,000",
               "> 10,000",
               "No data")
jobscolor <- colorBin("YlGn", domain = artsjobs$ArtsJobs, bins = jobsbins)

jobspercapbins <- c(0, 5, 10, 15, 20, 25, 50)
jobspercaplabels <- c("< 5",
               "5 - 10",
               "10 - 15",
               "15 - 20",
               "20 - 25",
               "> 25",
               "No data")
jobspercapcolor <- colorBin("YlGn", domain = jobs_per_cap$jobsPerCap, bins = jobspercapbins)
```



```{r make-map}
map <- leaflet(width = "100%") %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  
  # handling different layers
  addLayersControl(baseGroups = c("Arts Industry GDP",
                                  "Arts Industry GDP Per Capita",
                                  "Arts Industry Jobs",
                                  "Arts Industry Jobs Per 1,000 People"),
                   position = "topleft",
                   options = layersControlOptions(collapsed = FALSE)) %>%
  
  # Arts GDP map:
  addPolygons(data = gdp_map,
              stroke = TRUE,
              weight = 0.5,
              color = "#005a32",
              opacity = 1,
              fillColor = ~GDPColor(ArtsGDP),
              fillOpacity = 0.8,
              smoothFactor = 0.3,
              popup = ~info,
              highlightOptions = highlightOptions(color = "#000000", weight = 1.5,
                                                  bringToFront = TRUE, fillOpacity = 0.5),
              group = "Arts Industry GDP") %>%
  addLegend("topleft",
            opacity = 0.8,
            colors = c("#ffffcc", "#d9f0a3", "#addd8e", "#78c679", "#31a354", "#006837", "#888888"),
            title = "GDP of the Arts Industry (2021)",
            labels = GDPlabels,
            layerId = "Arts Industry GDP") %>%
  
    # Arts GDP per capita map:
  addPolygons(data = gdppercap_map,
              stroke = TRUE,
              weight = 0.5,
              color = "#005a32",
              opacity = 1,
              fillColor = ~GDPpercapColor(GDPperCap),
              fillOpacity = 0.8,
              smoothFactor = 0.3,
              popup = ~info,
              highlightOptions = highlightOptions(color = "#000000", weight = 1.5,
                                                  bringToFront = TRUE, fillOpacity = 0.5),
              group = "Arts Industry GDP Per Capita") %>%
  addLegend("topleft",
            opacity = 0.8,
            colors = c("#ffffcc", "#d9f0a3", "#addd8e", "#78c679", "#31a354", "#006837", "#888888"),
            title = "GDP of the Arts,<br>Per Capita (2021)",
            labels = GDPpercaplabels,
            layerId = "Arts Industry GDP Per Capita") %>%
  
  # Arts jobs map
  addPolygons(data = jobs_map,
              stroke = TRUE,
              weight = 0.5,
              color = "#005a32",
              opacity = 1,
              fillColor = ~jobscolor(ArtsJobs),
              fillOpacity = 0.8,
              smoothFactor = 0.3,
              popup = ~info,
              highlightOptions = highlightOptions(color = "#000000", weight = 1.5,
                                                  bringToFront = TRUE, fillOpacity = 0.5),
              group = "Arts Industry Jobs") %>%
  addLegend("topleft",
            opacity = 0.8,
            colors = c("#ffffcc", "#d9f0a3", "#addd8e", "#78c679", "#31a354", "#006837", "#888888"),
            title = "Jobs in the Arts (2021)",
            labels = jobslabels,
            layerId = "Arts Industry Jobs") %>%
  
  # Arts jobs per 1,000 people map
  addPolygons(data = jobspercap_map,
              stroke = TRUE,
              weight = 0.5,
              color = "#005a32",
              opacity = 1,
              fillColor = ~jobspercapcolor(jobsPerCap),
              fillOpacity = 0.8,
              smoothFactor = 0.3,
              popup = ~info,
              highlightOptions = highlightOptions(color = "#000000", weight = 1.5,
                                                  bringToFront = TRUE, fillOpacity = 0.5),
              group = "Arts Industry Jobs Per 1,000 People") %>%
  addLegend("topleft",
            opacity = 0.8,
            colors = c("#ffffcc", "#d9f0a3", "#addd8e", "#78c679", "#31a354", "#006837", "#888888"),
            title = "Jobs in the Arts,<br>Per 1,000 People (2021)",
            labels = jobspercaplabels,
            layerId = "Arts Industry Jobs Per 1,000 People") %>%
  
  #handling switching legends (from noamross on github)
  htmlwidgets::onRender("
    function(el, x) {
      var initialLegend = 'Arts Industry GDP' // Set the initial legend to be displayed by layerId
      var myMap = this;
      for (var legend in myMap.controls._controlsById) {
        var el = myMap.controls.get(legend.toString())._container;
        if(legend.toString() === initialLegend) {
          el.style.display = 'block';
        } else {
          el.style.display = 'none';
        };
      };
    myMap.on('baselayerchange',
      function (layer) {
        for (var legend in myMap.controls._controlsById) {
          var el = myMap.controls.get(legend.toString())._container;
          if(legend.toString() === layer.name) {
            el.style.display = 'block';
          } else {
            el.style.display = 'none';
          };
        };
      });
    }")
```

```{r run-map, include = TRUE, echo = FALSE}
map
```



